### ISSUE TITLE
I have issue with serial , why serial get it not the same on system app

### ISSUE THREAD

**Issue by Kimsoer** [karantanwar/unique_identifier#11]
I have issue with serial , why serial get it not the same on system app

**Comment by karantanwar** [comment]
Please elaborate

**Comment by OnofreTZK** [comment]
Hi, @karantanwar , i think my problem is the same -> I need to get the IMEI of the android device but when my code call "UniqueIdentifier.serial"  the value retrieved is: 332c74117207b320 and the IMEI on AVD is: 358240051111110.

**Comment by Tha14** [comment]
> 
> 
> Hi, @karantanwar , i think my problem is the same -> I need to get the IMEI of the android device but when my code call "UniqueIdentifier.serial" the value retrieved is: 332c74117207b320 and the IMEI on AVD is: 358240051111110.

You probably figured this out by now but this package is meant to etieve the unique device id, nothing to do with the IMEI(s) of the device
