### ISSUE TITLE
Outdated flutter_lints dependency causing error

### ISSUE THREAD

**Issue by saropa** [karantanwar/unique_identifier#15]
Hi, I am getting a package error and it appears to be caused by referencing an outdated flutter_lints package.

Because [project] depends on unique_identifier ^0.2.2 which depends on flutter_lints ^1.0.0, flutter_lints ^1.0.0 is required.
So, because [project] depends on flutter_lints ^2.0.1, version solving failed.

The latest (at the time of writing) is 2.0.1: https://pub.dev/packages/flutter_lints

Is it possible to fix this?

**Comment by guperini** [comment]
Same thing here. Could you please update the dependencies?

**Comment by paulobreim** [comment]
@karantanwar it is very unpleasant for you to propose to make a lib and simply abandon and ignore the users' notes.

YOU WROTE THIS IN PUB.DEV

Bugs & Requests 
If you encounter any bugs feel free to open an issue. Raise a ticket on github for suggestions. Pull request are also welcome.

**Comment by paulobreim** [comment]
@saropa @guperini 

Considering this lib is abandoned, I found an easier way to get the unique identifier, which is the same as this abandoned lib,

Use lib platform_device_id: ^1.0.1
In the program source import
import 'package:platform_device_id/platform_device_id.dart';
and then a single command to get the unique identifier:
String? deviceId = await PlatformDeviceId.getDeviceId;

Solved the problem, you can abandon this lib.

This lib has 229 likes against 25 likes.  ;-)

**Comment by saropa** [comment]
Thanks @paulobreim, that's a good workaround and we can remove this package completely.

**Comment by karantanwar** [comment]
Sorry for the delay... I have updated the lib. Thanks, @paulobreim for providing the alternative. platform_device_id is a good lib.

**Comment by saropa** [comment]
Thanks @karantanwar, I appreciate your work but I find the other package name to be more descriptive and provide a more comprehensive solution. 

The name "unique_identifier" suggests that the package is used to create, verify, or otherwise manage UUIDs in general.

**Comment by paulobreim** [comment]
> Sorry for the delay... I have updated the lib. Thanks, @paulobreim for providing the alternative. platform_device_id is a good lib.

Thank you. I am using your lib in 5 others app and t is very important because I use this number as key to identify the user, and don´t need to use user e-mail.  Is the first call that my app use.
