### ISSUE TITLE
iOS: the identifierForVendor is not the same after uninstalling the app

### ISSUE THREAD

**Issue by HamzaMihfad** [karantanwar/unique_identifier#16]
The `identifierForVendor` in iOS is not the same, it's not unique after uninstalling and installing the app again from App Store it gives you a new id.

**Comment by dmiedev** [comment]
The value in this property remains the same while the app (or another app from the same vendor) is installed on the iOS device. The value changes when the user deletes all of that vendor’s apps from the device and subsequently reinstalls one or more of them. The value can also change when installing test builds using Xcode or when installing an app on a device using ad-hoc distribution. Therefore, if your app stores the value of this property anywhere, you should gracefully handle situations where the identifier changes.

Source: https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor

**Comment by dmiedev** [comment]
@karantanwar this can be closed I think :]
