### ISSUE TITLE
release error

### ISSUE THREAD

**Issue by nitneuq33** [karantanwar/unique_identifier#3]
This is the error when I tried to release... I have no error before last flutter 1.10 upgrade

Execution failed for task ':unique_identifier:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\Users\utilisateur\AndroidStudioProjects\ouiquit_app\build\unique_identifier\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
  C:\Users\utilisateur\AndroidStudioProjects\ouiquit_app\build\unique_identifier\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

thank you

**Comment by ghost** [comment]
Same issue occuring for me as well.
Any solutions?

**Comment by nitneuq33** [comment]
I change in build.gradle of the plugin the min version 27 to 28

Le ven. 5 juin 2020 à 09:09, sanjay-dev-19 <notifications@github.com> a
écrit :

**Comment by ghost** [comment]
Working Fine Now. Thank You
@nitneuq33
