### ISSUE TITLE
Invalid plugin specification unique_identifier.

### ISSUE THREAD

**Issue by colkencon** [karantanwar/unique_identifier#9]
Currently getting this when trying to install unique_identifier

Invalid plugin specification unique_identifier.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
exit code 1

Flutter 2.2.0

**Comment by karantanwar** [comment]
this is fixed
